services:
  backend:
    image: registry.gitlab.com/trantrunghiu/xitthui-tool/backend:latest
    ports:
      - "4444:4444"
    volumes:
      - xitthuitool_backend_data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-4444}
    restart: always

  frontend:
    image: registry.gitlab.com/trantrunghiu/xitthui-tool/frontend:latest
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${FRONTEND_PORT:-3333}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:4444/api}
    depends_on:
      - backend
    restart: always

volumes:
  xitthuitool_backend_data:
